### ISSUE TITLE
Là một người quản lý tôi muốn có một danh sách các đề thi để dễ dàng thao tác xoá, sửa

### ISSUE THREAD

**Issue by hoanphi2201** [hoanphi2201/SoftEng-Assignments-nhom-10#26]
- [x] Viết html table

- [x] Viết css

- [x] API trả về dữ liệu

- [x] Báo lỗi

- [x] Thông báo có bao nhiêu đề thi

- [x] Phân trang

- [x] Xử lý nhiều trang

- [x] Css Đang load

**Comment by anhducc13** [comment]
Phần xử lý nhiều trang để xem hoàn nó oke các phần khác chưa đã để còn làm tiếp
----DUCTT----

**Comment by hoanphi2201** [comment]
Cần có thêm thuật toán giới hạn số phần tử hiển thị trên 1 trang (4 phần tử)
----HoanPhi----

**Comment by hoanphi2201** [comment]
Chú ý sử dụng các hàm đã có sẵn trong phần helper
----HoanPhi----

**Comment by anhducc13** [comment]
Đã xong hết, hoàn phí check hộ xem oke chưa, merge vào rồi đóng issues đi <3

**Comment by anhducc13** [comment]
Phân trang bị lỗi

**Comment by anhducc13** [comment]
Đã fix xong, lỗi tableLength kiểu string chưa convert thành number
