### ISSUE TITLE
Là một người quản lý tôi muốn có phần lọc danh sách đề thi theo môn, theo trạng thái để tiết kiệm thời gian quản lý

### ISSUE THREAD

**Issue by hoanphi2201** [hoanphi2201/SoftEng-Assignments-nhom-10#27]
- [x] Thay đổi số lượng bản ghi của một trang

- [x] Giao diện select box lọc 

- [x] API lọc theo yêu cầu

- [x] Xử lý khi thay đổi thuộc tính lọc

**Comment by anhducc13** [comment]
Xong issue này rồi bác

**Comment by hoanphi2201** [comment]
Sửa cái vừa comment xong pull request đi.

**Comment by hoanphi2201** [comment]
Kiểm tra lại phần search có lỗi khi enter gọi hàm filter 2 lần

**Comment by anhducc13** [comment]
fixed
