### ISSUE TITLE
Là một người quản lý tôi muốn có chức năng sắp xếp danh sách theo tên, số câu hỏi, ngày tạo... để tiết kiệm thời gian quản lý

### ISSUE THREAD

**Issue by hoanphi2201** [hoanphi2201/SoftEng-Assignments-nhom-10#28]
- [x] Giao diện button sắp xếp

- [x] API trả về dữ liệu sắp xếp

- [x] Thay đổi các button sắp xếp

**Comment by anhducc13** [comment]
Vấn đề: chỉ có 1 biến sortType mà có tới 4 trường cần sắp xếp, ko thể lưu sortType hiện tại của 1 trường được

**Comment by hoanphi2201** [comment]
Anh Đức cần làm 2 việc là display class 'fa-sort', 'fa-sort-asc', 'fa-sort-desc' (dùng [ngClass]). Và viết 1 hàm nhận 2 tham số sortField và sortType

**Comment by anhducc13** [comment]
t thấy cách của t là họp lý- ko cần hàm 2 tham số, chỉ cần 1

**Comment by hoanphi2201** [comment]
ok.
